### PR TITLE
Fix deprecation warning on Ember 2.1+ and update toolset

### LINKED ISSUE #1: Generates deprecation warning on Ember 2.1.0
DEPRECATION: The `initialize` method for Application initializer 'ember-i18n' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.

### PR DESCRIPTION
**Pull request by raido**
Updated Ember CLI to v2.2.0-beta.6 and Ember to 2.3.0.
Fix deprecation warning
Add unit tests

Closes #1

### CODE REVIEW

**Comment by raido** [comment]
cc @kellyselden

**Comment by kellyselden** [comment]
Thank you very much. The Brocfile can be removed.

**Comment by raido** [comment]
Yes, forgot that.

**Comment by raido** [comment]
@kellyselden - Brocfile removed.

**Comment by kellyselden** [comment]
Thank you.

**Comment by kellyselden** [comment]
v0.0.2 published

**Pull request merged**
